### ISSUE TITLE
AWSElasticBeanstalk managed policy missing permission

### ISSUE THREAD

**Issue by dustinfarris** [aws/aws-elastic-beanstalk-cli#68]
This is probably not the right place for this bug report, but:

I am following elastic beanstalk tutorial:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_express.html

The IAM user has the `arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk` policy attached and no other policy or role.

when i got to the `eb deploy` step, i get this error:

```
2021-03-19 20:54:09,798 (DEBUG) ebcli.lib.aws : Making api call: (s3, list_multipart_uploads) to region: us-east-2 with args:{'Bucket': 'elasticbeanstalk-us-east-2-391516812325', 'Prefix': 'autumnfarris/app-a5b63-210319_205406.zip'}
2021-03-19 20:54:09,896 (DEBUG) ebcli.lib.aws : Response: {'Error': {'Code': 'AccessDenied', 'Message': 'Access Denied'}, 'ResponseMetadata': {'RequestId': '7RMZJPYXX6M83RGM', 'HostId': 'eXLO9h99qt5GySVFmAt2zQ13i20eeYQJ2yM/d+UilWnSkt0mfziQz3wQkoCugK8moPe7/j6DKPA=', 'HTTPStatusCode': 403, 'date': 'Sat, 20 Mar 2021 03:54:09 GMT', 'RetryAttempts': 0}}
```

it looks like the managed policy does not include the s3 `ListBucketMultipartUploads` permission.

**Comment by Palakpatel67** [comment]
@dustinfarris  Thanks for reaching out. `AdministratorAccess-AWSElasticBeanstalk` policy gives the user a full permission to create, modify and delete EB applications, environments etc. If your source code file size is greater than 7mb, EB CLI upload your source code in multiple parts to take advantage of S3’s multipart uploads. EB CLI make a call to `ListBucketMultipartUploads` operation on behalf of customer, and this operation is not included in AdministratorAccess-AWSElasticBeanstalk policy, as this policy is designed to support the opeartions required for EB service. In the meantime the workaround for this issue is that you can allow your IAM user  to make a request to `ListBucketMultipartUploads` operation. I will talk to my team and see what we can do here. Thanks!

**Comment by dustinfarris** [comment]
Thanks for the explanation ❤️ — I ended up doing just that.

**Comment by notxt** [comment]
@Palakpatel67 thank you so much! We were just banging our head against this one!

To anyone else debugging try running the command with `--debug` and look for `list_multipart_uploads` followed by the S3 403 error to confirm

@Palakpatel67 does this seem like something that will be added to the role? We created a "patch" policy and added to fix this, does that seem like a good solution?

**Comment by NihalM99** [comment]
Hi @dustinfarris  I have followed the steps listed in https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_express.html . With the IAM user having the `arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk` role and no other role . Was able to run `eb deploy` without any errors.Please reopen if you are still facing the issue . 
![Screenshot 2023-08-27 at 8 17 55 PM](https://github.com/aws/aws-elastic-beanstalk-cli/assets/97417949/48f992c6-6865-47c4-b13f-5aee8c16b82d)
![Screenshot 2023-08-27 at 8 18 34 PM](https://github.com/aws/aws-elastic-beanstalk-cli/assets/97417949/0353c68a-a5a2-44a8-a77c-d6e7f96a3ec5)

**Comment by colinbjohnson** [comment]
@Palakpatel67 @NihalM99 - would it be possible to reopen this issue? I had the same issue described above and resolved it by adding the following snippet:

```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Action": [
				"s3:ListBucketMultipartUploads"
			],
			"Resource": "arn:aws:s3:::elasticbeanstalk-*"
		}
	]
}
```

**Comment by barkey2121** [comment]
@colinbjohnson was this the only permission you added for S3? This didn’t resolve my issue when trying to ‘eb deploy’ my app. I’m thinking I might have permissions interfering with others. 

error: 
ERROR: NotAuthorizedError - Operation Denied. User: arn:aws:iam::********:user/******** is not authorized to perform: s3:ListBucketMultipartUploads on resource: "arn:aws:s3:::elasticbeanstalk-us-east-1-*******" because no permissions boundary allows the s3:ListBucketMultipartUploads action

**Comment by Infinoid** [comment]
This is still an issue, we ran into it today while deploying a compiled Go binary (178MB).  The `arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk` policy was insufficient:

```
ERROR: NotAuthorizedError - Operation Denied. User: arn:aws:iam::$ACCOUNT:user/$USERNAME is not authorized to perform: s3:ListBucketMultipartUploads on resource: "arn:aws:s3:::elasticbeanstalk-us-east-1-$ACCOUNT" because no identity-based policy allows the s3:ListBucketMultipartUploads action
```

Adding another policy with `s3:ListBucketMultipartUploads`, as described [here](https://github.com/aws/aws-elastic-beanstalk-cli/issues/68#issuecomment-2576836076), worked perfectly.

I wonder if @NihalM99's test in [this comment](https://github.com/aws/aws-elastic-beanstalk-cli/issues/68#issuecomment-1694943299) uploaded a file smaller than 7MB, and thus, didn't trigger the bug.

Please reopen.
