### ISSUE TITLE
We highly recommend using the EB CLI installation scripts that you can find at https://github.com/aws/aws-elastic-beanstalk-cli-setup.  The setup scripts will remedy this by using a virtualenv for all eb-cli commands, so you won't run into this conflict moving forward.

### ISSUE THREAD

**Issue by specialorange** [aws/aws-elastic-beanstalk-cli#71]
Please update the docs then -
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install-osx.html

We highly recommend using the EB CLI installation scripts that you can find at https://github.com/aws/aws-elastic-beanstalk-cli-setup.  The setup scripts will remedy this by using a virtualenv for all eb-cli commands, so you won't run into this conflict moving forward.

Meanwhile, we have noted this issue and will be working to fix it in the coming weeks.  Thank you for bringing this to our attention!

_Originally posted by @jsheld in https://github.com/aws/aws-elastic-beanstalk-cli/issues/2#issuecomment-574818732_

**Comment by Palakpatel67** [comment]
@specialorange thanks for reaching out. Our docs have been updated to recommend installing EB CLI using the EB CLI installation script. 

Doc links: 
[Manually Install the EB CLI](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install-advanced.html#:~:text=to%20install%20the%20eb%20cli%2C%20we%20recommend%20using%20the%20eb%20cli%20setup%20scripts.%20if%20the%20setup%20scripts%20aren't%20compatible%20with%20your%20development%20environment%2C%20manually%20install%20the%20eb%20cli.)
[Install the EB CLI using setup scripts](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html#:~:text=CLI-,install%20the%20eb%20cli%20using%20setup%20scripts,-The)

Closing this issue here. Feel free to reopen it if you have any questions. 
Thanks!
