### ISSUE TITLE
eb create --instance-types not working

### ISSUE THREAD

**Issue by shaicoleman** [aws/aws-elastic-beanstalk-cli#73]
### Description

Running `eb create` with the `--instance-types` parameter does not set the instance type.

### Steps to reproduce

Run `eb create testenv --debug --single --instance-types t3.medium`

In the debug logs there is no mention of instance type, so it seems it just isn't passed to the API.

### Observed result

Instance type is `t2.micro`

Please provide command output with `--debug` flag set.

### Expected result

Instance type should be `t3.medium`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04
2. EBCLI version: EB CLI 3.19.4 (Python 3.8.5)
3. Region: eu-west-1
4. Platform: Ruby 2.7 running on 64bit Amazon Linux 2

**Comment by plafue** [comment]
FWIW, if i understand the code correctly `--instance-types` seems to only apply to spot instances:

https://github.com/aws/aws-elastic-beanstalk-cli/blob/8d085af91634cb776ae551f45c6213b764d935f7/ebcli/objects/requests.py#L342-L346

while `--instance_type` (although deprecated) seems to affect regular launch configurations:

https://github.com/aws/aws-elastic-beanstalk-cli/blob/8d085af91634cb776ae551f45c6213b764d935f7/ebcli/objects/requests.py#L204-L208

**Comment by Palakpatel67** [comment]
@shaicoleman thanks for reaching out.  

EB CLI provides two different options to specify instance type for environment.

* `--instance_type`
* `--instance-types`

`--instance-types` option is coupled with `--enable-spot` option. So if you haven't specified `--enable-spot` with `--instance-types` option it will be ignored.

In your case you can use first option `--instance_type`, which will create enviornment with the specified instance type. 

```   
eb create testenv --debug --single --instance_type t3.medium
```

Although  `--instance_type` option is obsolete and we recommend using `--instance-types` option. 

[Elastic Beanstalk Docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-create.html#:~:text=the%20--instance_type%20option%20is%20obsolete.%20it's%20replaced%20by%20the%20newer%20and%20more%20powerful%20--instance-types%20option.)

Closing this issue here. Feel free to reopen it if you have any questions.

Thanks!

**Comment by shaicoleman** [comment]
I tried `--instance-type` and that didn't work, but `--instance_type` does work.
`--instance-type` should return an error to prevent confusion.
