### ISSUE TITLE
eb local setenv doesn't support quote escaped environment variables

### ISSUE THREAD

**Issue by gitmalong** [aws/aws-elastic-beanstalk-cli#83]
```
$ eb local setenv MATRIX=[1,2,3]
zsh: no matches found: MATRIX=[1,2,3]
```

So I try to escape it

```
$ eb local setenv MATRIX="[1,2,3]"
ERROR: InvalidSyntaxError - You must use the format KEY=VALUE to set an environment variable. Variables must start with a letter.
```

**Comment by Mickeypeng** [comment]
@gitmalong Thanks for reaching out to us. Actually this has nothing to do with escaping, it is a tricky bug caused by "," symbol. The command eb local setenv can accept multiple variables separated by comma: it will split using comma to decide how many variables are there. Therefore, when you input matrix as environment variable, the EB CLI will think it's three variables, since it has seen three commas. And that cause problems. Unfortunately we don't have a solution for now.
Thanks again for reporting this problem. We are working on it now.

**Comment by darioseidl** [comment]
I was facing the same issue, trying to set a variable containing a comma (or a space) would always return

> ERROR: InvalidSyntaxError - You must use the format KEY=VALUE to set an environment variable. Variables must start with a letter.

I also tried to escape the comma or space with a backslash or two, but that didn't work either. Is this supported in any way now?

The [docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-setenv.html) just say

> If the value contains a [special character](http://tldp.org/LDP/abs/html/special-chars.html), you must escape that character by preceding it with a \ character.

but it doesn't specify which characters are "special" in this context. Not all characters that a mentioned in the link cause problems, for example, a dot works without escaping.
