### ISSUE TITLE
eb config save --format json produces a yaml file

### ISSUE THREAD

**Issue by dennisvang** [aws/aws-elastic-beanstalk-cli#94]
### Description

When I call `eb config save` with `--format json`, I still get a YAML file:

```
eb config save my-env --format json

Enter desired name of configuration.
(default is "my-env-sc"): 

Configuration saved at: /home/abc/Documents/.../.elasticbeanstalk/saved_configs/my-env-sc.cfg.yml
```
It's not just the extension: the file actually does contain YAML.

### Steps to reproduce

Call `eb config save <environment name> --format json`

### Observed result

see above

### Expected result

I expected a JSON file.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu
2. EBCLI version: EB CLI 3.20.2 (Python 3.8.1)

**Comment by Mickeypeng** [comment]
Hi dennisvang@, thanks for reaching out! Actually the the` eb config save` command and `eb config --update` command are working on two different concepts: The former one is used to save a saved configuration and the latter one is used to modify current environment configuration. Therefore the YAML files produced by the former command can’t be used by the latter one.
The latter command is developed because some customers want to modify current environment configuration programmatically. Usually these modifications are quite small so it’s not efficient to let customers input the whole environment configuration. Instead, they will only need to input the options they want to modify. For the exact format of `eb config --update`, here is our doc: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-config.html 
In addition, if you want to apply a saved configuration (i.e. the one you saved using eb config save), here is our doc: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-configuration-savedconfig.html
